[package]
name = "ffrostfall/sduioajfodslg"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
vide = "alicesaidhi/vide@0.3.1-lite.649"
ui-labs = "pepeeltoro41/ui-labs@2.3.0"
